### ISSUE TITLE
Usage in VisualStudio C++

### ISSUE THREAD

**Issue by adamsepp** [klauer/PMD101#1]
Hi, I want to write a small C++ programm (in VisualStudio c++) to control 2 PMD101 modules.
Since I'm a C programmer which workes usually only on B&R real time controllers I to not have too much experience on your code structure...
I'm interested in how you build this code and if it makes sense for me to create an Visual Studio Project and import some of this project?
BR, Josef

**Comment by klauer** [comment]
Hi Josef, I'm afraid this library won't be of much use to you. It's specifically for the EPICS (Experimental Physics
and Industrial Control System) which you can read about more here: https://epics-controls.org/resources-and-support/documents/epics-faq/#What_is_EPICS

**Comment by adamsepp** [comment]
Hi, ok, thanks for this information.
This library is still helpful for me, as a reference for my application... Thanks :-)

**Comment by klauer** [comment]
No problem - and good luck 👍
